#!/usr/bin/env bash
#this script is created to take a argument from the command line and ping it.
if [ $# -ne 2 ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}" >&2
    exit 1
fi

ping -c 5 "$1"