#!/usr/bin/env bash
# This script is displaying "Best School" 10 times

Hour=0
Minutes=1
while [ $Hour -le 11 ]
do
	echo "Hour: $Hour"
	while [ $Minutes -le 59 ]
	do
		echo "$Minutes"
		((Minutes++))
	done
	Minutes=1
	((Hour++))
done
